#!/bin/sh

if [ -f /etc/zaf.conf  ]; then
	. /etc/zaf.conf
else
	echo "Missing config file /etc/zaf.conf! Exiting."
	exit 2
fi

. ${ZAF_LIB_DIR}/zaf.lib.sh

case $1 in

check-agent-config)
	zaf_check_agent_config
	;;

update)
	zaf_update_repo
	;;

show)
	if [ -z "$2" ]; then
		zaf_show_installed_plugins
	else
		zaf_show_plugin "$2"
	fi
	;;

list)
	zaf_list_plugins
	;;

list-items)
	if [ -z "$2" ]; then
		zaf_list_items
	else
		zaf_list_plugin_items "$2"
	fi
	;;

test-items)
	zaf_show_plugin "$2" tst
	;;

install)
	zaf_install_plugin "$2"
	;;

remove)
	zaf_remove_plugin "$2"
	;;

self-upgrade)
	curl -s https://raw.githubusercontent.com/limosek/zaf/master/install.sh | sh
	;;

*)
	echo "$0 update			To update repo" 
	echo "$0 list			To list installed plugins"
	echo "$0 show [plugin]		To show installed plugins or plugin info"
	echo "$0 list-items [plugin]	To list all suported items [for plugin]"
	echo "$0 test-items plugin	To test all suported items for plugin"
	echo "$0 install plugin		To install plugin"
	echo "$0 remove plugin		To remove plugin" 
	echo "$0 self-upgrade		To self-upgrade zaf"
	;;

esac

