#!/bin/sh

. $(dirname $0)/preload.sh

help() {
	zaf_err "$0 seconds cmd..."
}

seconds=$1
shift
[ -z "$*" ] && help

parms=$(echo $*|tr -d ' ')
if ! zaf_fromcache "$parms"; then
	$@ | zaf_tocache_stdin "$parms" "$seconds"
fi

